// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.8
// source: pb/actionpb/action.proto

package actionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	commonpb "pb/commonpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionProcessV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResolveParams []*commonpb.ResolveParam `protobuf:"bytes,2,rep,name=resolve_params,json=resolveParams,proto3" json:"resolve_params,omitempty"`
}

func (x *ActionProcessV1Request) Reset() {
	*x = ActionProcessV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_actionpb_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionProcessV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProcessV1Request) ProtoMessage() {}

func (x *ActionProcessV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_actionpb_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProcessV1Request.ProtoReflect.Descriptor instead.
func (*ActionProcessV1Request) Descriptor() ([]byte, []int) {
	return file_pb_actionpb_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionProcessV1Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionProcessV1Request) GetResolveParams() []*commonpb.ResolveParam {
	if x != nil {
		return x.ResolveParams
	}
	return nil
}

type ActionProcessV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body           []byte                   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ClientResponse *commonpb.ClientResponse `protobuf:"bytes,2,opt,name=client_response,json=clientResponse,proto3" json:"client_response,omitempty"`
}

func (x *ActionProcessV1Response) Reset() {
	*x = ActionProcessV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_actionpb_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionProcessV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProcessV1Response) ProtoMessage() {}

func (x *ActionProcessV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_actionpb_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProcessV1Response.ProtoReflect.Descriptor instead.
func (*ActionProcessV1Response) Descriptor() ([]byte, []int) {
	return file_pb_actionpb_action_proto_rawDescGZIP(), []int{1}
}

func (x *ActionProcessV1Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ActionProcessV1Response) GetClientResponse() *commonpb.ClientResponse {
	if x != nil {
		return x.ClientResponse
	}
	return nil
}

var File_pb_actionpb_action_proto protoreflect.FileDescriptor

var file_pb_actionpb_action_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x18, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x16,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x6e, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x3f, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x67, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x54, 0x0a, 0x0f, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x56, 0x31, 0x12, 0x1e, 0x2e,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_actionpb_action_proto_rawDescOnce sync.Once
	file_pb_actionpb_action_proto_rawDescData = file_pb_actionpb_action_proto_rawDesc
)

func file_pb_actionpb_action_proto_rawDescGZIP() []byte {
	file_pb_actionpb_action_proto_rawDescOnce.Do(func() {
		file_pb_actionpb_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_actionpb_action_proto_rawDescData)
	})
	return file_pb_actionpb_action_proto_rawDescData
}

var file_pb_actionpb_action_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_actionpb_action_proto_goTypes = []interface{}{
	(*ActionProcessV1Request)(nil),  // 0: action.ActionProcessV1Request
	(*ActionProcessV1Response)(nil), // 1: action.ActionProcessV1Response
	(*commonpb.ResolveParam)(nil),   // 2: common.ResolveParam
	(*commonpb.ClientResponse)(nil), // 3: common.ClientResponse
}
var file_pb_actionpb_action_proto_depIdxs = []int32{
	2, // 0: action.ActionProcessV1Request.resolve_params:type_name -> common.ResolveParam
	3, // 1: action.ActionProcessV1Response.client_response:type_name -> common.ClientResponse
	0, // 2: action.ActionProcessor.ActionProcessV1:input_type -> action.ActionProcessV1Request
	1, // 3: action.ActionProcessor.ActionProcessV1:output_type -> action.ActionProcessV1Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_actionpb_action_proto_init() }
func file_pb_actionpb_action_proto_init() {
	if File_pb_actionpb_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_actionpb_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionProcessV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_actionpb_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionProcessV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_actionpb_action_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_actionpb_action_proto_goTypes,
		DependencyIndexes: file_pb_actionpb_action_proto_depIdxs,
		MessageInfos:      file_pb_actionpb_action_proto_msgTypes,
	}.Build()
	File_pb_actionpb_action_proto = out.File
	file_pb_actionpb_action_proto_rawDesc = nil
	file_pb_actionpb_action_proto_goTypes = nil
	file_pb_actionpb_action_proto_depIdxs = nil
}
